### ISSUE TITLE
Create tutorial about the data

### ISSUE THREAD

**Issue by lydiang** [InsightSoftwareConsortium/GetYourBrainStraight#10]
Create a "do at your own pace" tutorial (a collection of jupyter notebooks)
- Introduction of the Allen CCFv3 using ITK and related tools to open and visualize the image volume - includes some background principles of biomedical imaging data
- Introduction to ITK registration framework and show examples of transform and resampling, rigid, affine, deformable
- Demonstrate the use of ANTs (on STPT - simply problem) to register one example dataset and how to use the transform output to resample the image and to transform annotation to/fro between the spaces
- Introduction of the fMOST dataset using ITK and related tools to open/visualize. Point out the specific properties/challenges of this dataset 

Infrastructure to run these notebooks such as Binder, or BIL hosting

**Comment by thewtex** [comment]
xref @jeffduda's https://github.com/jeffduda/GetYourBrainPipelined

**Comment by thewtex** [comment]
Todo add description: https://insightsoftwareconsortium.github.io/GetYourBrainStraight/HCK01_2022_Virtual/Tutorials/

**Comment by thewtex** [comment]
Done: https://insightsoftwareconsortium.github.io/GetYourBrainStraight/HCK01_2022_Virtual/Tutorials/fMOSTIntroduction/
