### ISSUE TITLE
Expand ways to participate and pre-meeting activities

### ISSUE THREAD

**Issue by lydiang** [InsightSoftwareConsortium/GetYourBrainStraight#11]
@thewtex 

Given the feedback we received during the Morphology working group meeting and subsequently. 
Let's consider broadening ways of participation. This is what I was thinking

**Ways to participate:**
* Give a tutorial of your registration tools (pre-recorded or live presentation) along with example code and recipes to teach a data analyst how to run your tool and use the output on the challenge dataset and/or another open dataset
* Contribute a registration pipeline resource that can be deploy on BIL resources to register the challenge dataset (preferred) and/or another open dataset
* Come and learn about registration from experts in the field.

For the NWB hackathon, a pre-meeting meet-up was helpful for the participant to solidify their plans, meet each other and for the organizer some insight of what the participants are wanting to do and how we need to prepare for. As such we need to
- Set a please pre-register by date and have pre-meeting zoom meeting (mid -March?)
- At the meeting we present a rough calendar of daily activities etc. and each participant get a couple of meetings to discuss their plan and Q&A.

Thoughts?

**Comment by thewtex** [comment]
> **Ways to participate:**

@lydiang great idea. I added these with pointers to the detailed sections here: https://github.com/InsightSoftwareConsortium/GetYourBrainStraight/pull/12

> a pre-meeting meet-up was helpful for the participant to solidify their plans, meet each other and for the organizer some insight of what the participants are wanting to do and how we need to prepare for

This is a good idea. How about 12 PM Pacific, Monday, the 21st?

 > - Set a please pre-register by date and have pre-meeting zoom meeting (mid -March?)

The pre-register date is currently April 2nd.

https://insightsoftwareconsortium.github.io/GetYourBrainStraight/HCK01_2022_Virtual/#when-where-how-much

Do you think it should be earlier?

**Comment by lydiang** [comment]
Here is link for the zoom meeting for Monday 21 at 12PM PT
 https://alleninstitute-org.zoom.us/j/97684575561?pwd=QVZSK3VEcXlEL3c2QW13b2c3U3pvdz09
 
 Ok with pre-register date need to encourage folks to attend the pre-hackathon meeting

**Comment by thewtex** [comment]
@lydiang yes. Please review #14 that suggests example tutorial topics including data descriptions.
