### ISSUE TITLE
Add description for metadata preservation tutorial

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/GetYourBrainStraight#16]
https://insightsoftwareconsortium.github.io/GetYourBrainStraight/HCK01_2022_Virtual/Tutorials/

**Comment by thewtex** [comment]
Interactive content todos:

1. [ ] Jupyter notebook on how to read the image with ITK Python, describe the metadata, how it is accessed, LPS orientation, the spatial image metadata concepts from the ITK Software Guide
2. [ ] Notebook on how to use the orient filter in Python
3. [ ] Jupyter notebook on reading the image with nibabel, anatomical orientation, spatial metadata, converting between nibabel and itk
4. [ ] Jupyter notebook on reading an image, accessing metadata, in C++, `itk::ReadImage`, `->Print()`, `GetSpacing`, `GetImportBuffer`, etc.

**Comment by dzenanz** [comment]
> Notebook on how to use the orient filter in Python

@thewtex this requires building from source, as [the feature](https://github.com/InsightSoftwareConsortium/ITK/pull/3205) was added after 5.3RC3.

**Comment by thewtex** [comment]
> after 5.3RC3.

We can tag / release 5.3RC4 for the hackathon.

**Comment by thewtex** [comment]
Presentation material: https://docs.google.com/presentation/d/1Mo_yHmJ7Uai2DKAO2VTyAm56V9KdI-Wx5xVgc9gljmQ/edit#slide=id.p28
