### ISSUE TITLE
Add a link to curated fMOST datasets on BIL

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/GetYourBrainStraight#3]

**Comment by lydiang** [comment]
@thewtex 

I am currently uploading all the data to BIL (will be done before presentation in the morning)

The data is loaded here: /bil/proj/hackathon/2022_GYBS/data
There are two subdirectories:
1. reference: containing the target 25 micron CCFv3
2. subject: containing each of the dataset to be registered

Would you help me add to challenge page?

![image](https://user-images.githubusercontent.com/8552673/155240968-adcbb01b-7034-4a8a-b8b2-a807f28ee13a.png)

**Comment by thewtex** [comment]
@lydiang fantastic!

Is there an http link?

**Comment by lydiang** [comment]
I think you need to login to BIL

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
