### ISSUE TITLE
Switch out the cells in the logo?

### ISSUE THREAD

**Issue by lydiang** [InsightSoftwareConsortium/GetYourBrainStraight#5]
@thewtex 

Are you willing to entertain switching out the images in the logo with these two cells
![17782_3352-X11384-Y16404_ccf_combined_atlas_colors](https://user-images.githubusercontent.com/8552673/155248508-f22c1b80-de6b-4851-ae01-5e7eb0d2de6d.png)
![17782_3352-X11384-Y16404_ccf_combined_view](https://user-images.githubusercontent.com/8552673/155248517-c7a5eb98-afbb-42dd-8c0a-3a9efd9c63d8.png)
![182724_2526-X7529-Y21792_ccf_combined_atlas_colors](https://user-images.githubusercontent.com/8552673/155248522-4123703e-3baa-4be3-89dd-4d94bbc7e5c0.png)
![182724_2526-X7529-Y21792_ccf_combined_view](https://user-images.githubusercontent.com/8552673/155248528-afb719b9-7d0b-451c-9c4f-2bbfa59d615d.png)
?

**Comment by thewtex** [comment]
@lydiang absolutely, please review: https://github.com/InsightSoftwareConsortium/GetYourBrainStraight/pull/7
